### ISSUE TITLE
Graph Explorer experiences runtime crash in browser

### ISSUE THREAD

**Issue by mmore500** [devosoft/Empirical#235]
i.e., `examples/web/Graph.cc`

Here's the trace:
```
graph-explorer.js:1577 Uncaught (in promise) TypeError: Cannot read property 'getContext' of null
    at Array.ASM_CONSTS (https://devosoft.github.io/graph-explorer/graph-explorer.js:1577:111)
    at _emscripten_asm_const_ii (https://devosoft.github.io/graph-explorer/graph-explorer.js:1628:26)
    at __ZN3emp3web6Canvas10CanvasInfo12TargetCanvasEv (wasm-function[198]:36)
    at __ZN3emp3web6Canvas10CanvasInfo9TriggerJSEv (wasm-function[568]:33)
    at __ZN3emp3web8internal10WidgetInfo11ReplaceHTMLEv (wasm-function[122]:374)
    at __ZN3emp3web8internal10WidgetInfo10DoActivateEb (wasm-function[115]:38)
    at __ZN3emp3web8internal9TableInfo8AddChildEmmNS0_6WidgetE (wasm-function[524]:609)
    at __ZN3emp3web8internal9TableInfo8AddChildENS0_6WidgetE (wasm-function[523]:98)
    at __ZN3emp3web8internal9TableInfo6AppendENS0_6WidgetE (wasm-function[511]:24)
    at __ZN3emp3web8internal10WidgetInfo6AppendINS0_5TableEEENS0_6WidgetERKT_ (wasm-function[498]:62)
ASM_CONSTS @ graph-explorer.js:1577
_emscripten_asm_const_ii @ graph-explorer.js:1628
__ZN3emp3web6Canvas10CanvasInfo12TargetCanvasEv @ wasm-0015657a-198:20
__ZN3emp3web6Canvas10CanvasInfo9TriggerJSEv @ wasm-0015657a-568:19
__ZN3emp3web8internal10WidgetInfo11ReplaceHTMLEv @ wasm-0015657a-122:177
__ZN3emp3web8internal10WidgetInfo10DoActivateEb @ wasm-0015657a-115:19
__ZN3emp3web8internal9TableInfo8AddChildEmmNS0_6WidgetE @ wasm-0015657a-524:283
__ZN3emp3web8internal9TableInfo8AddChildENS0_6WidgetE @ wasm-0015657a-523:48
__ZN3emp3web8internal9TableInfo6AppendENS0_6WidgetE @ wasm-0015657a-511:14
__ZN3emp3web8internal10WidgetInfo6AppendINS0_5TableEEENS0_6WidgetERKT_ @ wasm-0015657a-498:33
__ZN3emp3web6WidgetlsIRNS0_5TableEEES1_OT_ @ wasm-0015657a-342:22
__ZN11GraphDriverC2Ev @ wasm-0015657a-103:269
__GLOBAL__sub_I_graph_explorer_web_cc @ wasm-0015657a-807:14
Module.__GLOBAL__sub_I_graph_explorer_web_cc @ graph-explorer.js:5674
func @ graph-explorer.js:1667
callRuntimeCallbacks @ graph-explorer.js:1249
ensureInitRuntime @ graph-explorer.js:1280
doRun @ graph-explorer.js:5883
run @ graph-explorer.js:5903
runCaller @ graph-explorer.js:5811
removeRunDependency @ graph-explorer.js:1404
receiveInstance @ graph-explorer.js:1498
receiveInstantiatedSource @ graph-explorer.js:1519
Promise resolved (async)
createWasm @ graph-explorer.js:1535
Module.asm @ graph-explorer.js:1565
(anonymous) @ graph-explorer.js:5671
```

**Comment by mmore500** [comment]
Update: the javascript runs fine in browser (Chrome and Firefox) when compiled in debug mode. Otherwise, it crashes in both browsers. Firefox gives a slightly more helpful trace...
```
TypeError: canvas is null
[Learn More]
Graph.js:1:14644
ASM_CONSTS<
http://localhost:8003/Graph.js:1:14644
_emscripten_asm_const_ii
http://localhost:8003/Graph.js:1:17827
rd
http://localhost:8003/Graph.js:7:1
wm
http://localhost:8003/Graph.js:7:1
sc
http://localhost:8003/Graph.js:7:1
kc
http://localhost:8003/Graph.js:7:1
ul
http://localhost:8003/Graph.js:7:1
tl
http://localhost:8003/Graph.js:7:1
hl
http://localhost:8003/Graph.js:7:1
qm
http://localhost:8003/Graph.js:7:1
Ug
http://localhost:8003/Graph.js:7:1
Zb
http://localhost:8003/Graph.js:7:1
Yb
http://localhost:8003/Graph.js:7:1
os
http://localhost:8003/Graph.js:8:1
func
http://localhost:8003/Graph.js:1:18598
callRuntimeCallbacks
http://localhost:8003/Graph.js:1:12115
ensureInitRuntime
http://localhost:8003/Graph.js:1:12663
doRun
http://localhost:8003/Graph.js:16:5100
run
http://localhost:8003/Graph.js:16:5412
runCaller
http://localhost:8003/Graph.js:16:4191
removeRunDependency
http://localhost:8003/Graph.js:1:13849
applyMemoryInitializer
http://localhost:8003/Graph.js:16:3135
xhr_onload
http://localhost:8003/Graph.js:1:3245
```

**Comment by mmore500** [comment]
RE: chatting with @mercere99 on Monday I did some trial and error testing with flags that differ between debug mode and optimized mode for web compiling.

Here are the relevant components of the Makefile:
```
OFLAGS_web_debug := -g4 -pedantic -Wno-dollar-in-identifier-extension -s TOTAL_MEMORY=67108864 -s ASSERTIONS=2 -s DEMANGLE_SUPPORT=1 -s WASM=0 -Wnon-virtual-dtor -Wcast-align -Woverloaded-virtual -Wconversion -Weffc++
 # -s SAFE_HEAP=1
OFLAGS_web_opt := -Os -DNDEBUG -s TOTAL_MEMORY=67108864 -s WASM=0
```

In this state, the web executable runs fine when compiled in debug mode but crashes when compiled in optimized mode. 

Removing the `-Os` flag from `OFLAGS_web_opt` causes the web executable to not crash when compiled in optimized mode.

Adding the `-Os` flag to `OFLAGS_web_debug` causes the web executable to crash when compiled in debug mode.

Removing `-s WASM=0` from the `OFLAGS_web_debug` causes the web executable to crash when compiled in optimized mode.

**Comment by mmore500** [comment]
I believe the plan is to wait on digging deeper into this until we get around to ripping out lots of Empirical web internals to take advantage of [new Emscipten api features](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-code-call-javascript-from-native) e.g., [particularly `EM_JS`](https://github.com/emscripten-core/emscripten/issues/6147).

**Comment by mmore500** [comment]
Once we steamroll this issue, we'll want to remember to go over and apply the fix to our deployed graph explorer application here [https://github.com/devosoft/graph-explorer](https://github.com/devosoft/graph-explorer).

**Comment by mercere99** [comment]
-Os indicates that the executable should be optimized for size.  I wonder if it makes certain assumptions about memory management that contradict our own assumptions.

The specific optimizations used in -Os are listed here: https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html

I think the next step in tracking down the problem would be to do a binary search through the specific optimizations and see which ones cause it to break.

One simple test would be to try -O1 and then -O2.  Based off of which combination of them work / break, we should be able to narrow it much further in.

ALSO if, for example, -O1 works, we can use that as a default until we fix the underlying problem.

**Comment by mmore500** [comment]
* `-O0` works
* `-O1` works but gives the warning `Invalid asm.js: Expected shift of word size` RE the following line
  *         `HEAP32[((dest)>>2)]=((HEAP32[((src)>>2)])|0);`
* `-O2` and `-O3` crashes

**Comment by mmore500** [comment]
The documentation states `-Os enables all -O2 optimizations except those that often increase code size` so we would need to search through a lot of flags! I wonder if it might not be a particular flag but just a combination of optimizations that somehow causes the canvas to be accessed before it is ready (which sounds consistent with issues you mentioned having tackled earlier). In that case, it might not even be possible to track down a particular flag that is causing the issue.

**Comment by mercere99** [comment]
Interesting.  I'm not sure about the warning, but we can track it down by tearing out code until it goes away.  Maybe tomorrow or Monday we can try that.

For the error, we've narrowed it down to the optimizations below.  I think we could just turn out half of them and see if it break...  there's only 31 lines (the ones on the same line go together), so we could do it in 5 tests theoretically...  ;-)

-fcaller-saves 
-fcode-hoisting 
-fcrossjumping 
-fcse-follow-jumps  -fcse-skip-blocks 
-fdelete-null-pointer-checks 
-fdevirtualize  -fdevirtualize-speculatively 
-fexpensive-optimizations 
-fgcse  -fgcse-lm  
-fhoist-adjacent-loads 
-finline-small-functions 
-findirect-inlining 
-fipa-bit-cp  -fipa-cp  -fipa-icf 
-fipa-ra  -fipa-sra  -fipa-vrp 
-fisolate-erroneous-paths-dereference 
-flra-remat 
-foptimize-sibling-calls 
-foptimize-strlen 
-fpartial-inlining 
-fpeephole2 
-freorder-blocks-algorithm=stc 
-freorder-blocks-and-partition  -freorder-functions 
-frerun-cse-after-loop  
-fschedule-insns  -fschedule-insns2 
-fsched-interblock  -fsched-spec 
-fstore-merging 
-fstrict-aliasing 
-fthread-jumps 
-ftree-builtin-call-dce 
-ftree-pre 
-ftree-switch-conversion  -ftree-tail-merge 
-ftree-vrp

**Comment by mmore500** [comment]
What exactly flags "going together" mean?

**Comment by mercere99** [comment]
Just that you would turn them both on or both off at the same time.  Of course, if one of those pairs seems to be the problem, we'd probably keep going to see which on it is...  But whichever optimization turns out to be the problem, we should be able to read more about it and get a good insights as to what's going wrong.
