### ISSUE TITLE
Examine using catch tests within emscripten

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#94]
WIll Emscripten compile/run the catch tests?

**Comment by bocajnotnef** [comment]
So, I get several dozen lines of:

```Calling stub instead of signal()```

but hey, it works! (for `test_tools.cc` anyway)

**Comment by bocajnotnef** [comment]
Evo tests fail:

```
exception thrown: ReferenceError: alert is not defined,ReferenceError: alert is not defined
    at Array.ASM_CONSTS (/home/jgf/git/Empirical/tests/emcc-subtest-evo.js:1572:65)
    at _emscripten_asm_const_1 (/home/jgf/git/Empirical/tests/emcc-subtest-evo.js:1575:25)
    at Array.__ZN3emp6NotifyIJPKcNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEEvDpT_ (/home/jgf/git/Empirical/tests/emcc-subtest-evo.js:153258:12)
    at Object.dynCall_vii (/home/jgf/git/Empirical/tests/emcc-subtest-evo.js:354246:33)
    at invoke_vii (/home/jgf/git/Empirical/tests/emcc-subtest-evo.js:6487:26)
    at Array.__ZN3emp11NotifyErrorIJNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEEEEvDpT_ (/home/jgf/git/Empirical/tests/emcc-subtest-evo.js:151787:2)
    at Object.dynCall_vi (/home/jgf/git/Empirical/tests/emcc-subtest-evo.js:354239:32)
    at invoke_vi (/home/jgf/git/Empirical/tests/emcc-subtest-evo.js:6478:25)
    at Array.__ZN3emp6Config4ReadENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE (/home/jgf/git/Empirical/tests/emcc-subtest-evo.js:140577:15)
    at Object.dynCall_iii (/home/jgf/git/Empirical/tests/emcc-subtest-evo.js:354330:40)
/home/jgf/git/Empirical/tests/emcc-subtest-evo.js:97
      throw ex;
```

@mercere99 @emilydolson Any thoughts?

**Comment by bocajnotnef** [comment]
Hmm, looks like it's because there's no browser window for alert() to hit...

**Comment by bocajnotnef** [comment]
http://phantomjs.org/ may solve

will investigate

**Comment by bocajnotnef** [comment]
Additional question: can JS access/write to the filesystem?

@mercere99

**Comment by bocajnotnef** [comment]
Hmm, it does, it just doesn't play nicely with ofstream.good()

weird.

**Comment by bocajnotnef** [comment]
Looks like relative pathnames fail?

https://github.com/devosoft/Empirical/blob/jgf/testing/emcc/tests/minimal_reproduce.cc

I made sure 'temp' existed, but it won't write into it.
It's not 'cuz it's a new file, it'll create `temp.txt` just fine, but not `temp/temp.txt`

**Comment by emilydolson** [comment]
All of this seems to work fine now (in that the tests all now pass when compiled with Emscripten)
